// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.0--rc3
// source: notification.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ======= Запросы =======
type SetUpAuthTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserChatId    int64                  `protobuf:"varint,1,opt,name=user_chat_id,json=userChatId,proto3" json:"user_chat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetUpAuthTokenRequest) Reset() {
	*x = SetUpAuthTokenRequest{}
	mi := &file_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetUpAuthTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUpAuthTokenRequest) ProtoMessage() {}

func (x *SetUpAuthTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUpAuthTokenRequest.ProtoReflect.Descriptor instead.
func (*SetUpAuthTokenRequest) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{0}
}

func (x *SetUpAuthTokenRequest) GetUserChatId() int64 {
	if x != nil {
		return x.UserChatId
	}
	return 0
}

type ValidateAuthTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserChatId    int64                  `protobuf:"varint,1,opt,name=user_chat_id,json=userChatId,proto3" json:"user_chat_id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateAuthTokenRequest) Reset() {
	*x = ValidateAuthTokenRequest{}
	mi := &file_notification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateAuthTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateAuthTokenRequest) ProtoMessage() {}

func (x *ValidateAuthTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateAuthTokenRequest.ProtoReflect.Descriptor instead.
func (*ValidateAuthTokenRequest) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{1}
}

func (x *ValidateAuthTokenRequest) GetUserChatId() int64 {
	if x != nil {
		return x.UserChatId
	}
	return 0
}

func (x *ValidateAuthTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ConfirmEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmEmailRequest) Reset() {
	*x = ConfirmEmailRequest{}
	mi := &file_notification_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmEmailRequest) ProtoMessage() {}

func (x *ConfirmEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmEmailRequest.ProtoReflect.Descriptor instead.
func (*ConfirmEmailRequest) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{2}
}

func (x *ConfirmEmailRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type UpdateReceiveEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserChatId    int64                  `protobuf:"varint,1,opt,name=user_chat_id,json=userChatId,proto3" json:"user_chat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateReceiveEmailRequest) Reset() {
	*x = UpdateReceiveEmailRequest{}
	mi := &file_notification_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateReceiveEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateReceiveEmailRequest) ProtoMessage() {}

func (x *UpdateReceiveEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateReceiveEmailRequest.ProtoReflect.Descriptor instead.
func (*UpdateReceiveEmailRequest) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateReceiveEmailRequest) GetUserChatId() int64 {
	if x != nil {
		return x.UserChatId
	}
	return 0
}

type SetUpAuthTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetUpAuthTokenResponse) Reset() {
	*x = SetUpAuthTokenResponse{}
	mi := &file_notification_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetUpAuthTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUpAuthTokenResponse) ProtoMessage() {}

func (x *SetUpAuthTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUpAuthTokenResponse.ProtoReflect.Descriptor instead.
func (*SetUpAuthTokenResponse) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{4}
}

func (x *SetUpAuthTokenResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ValidateAuthTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateAuthTokenResponse) Reset() {
	*x = ValidateAuthTokenResponse{}
	mi := &file_notification_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateAuthTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateAuthTokenResponse) ProtoMessage() {}

func (x *ValidateAuthTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateAuthTokenResponse.ProtoReflect.Descriptor instead.
func (*ValidateAuthTokenResponse) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{5}
}

func (x *ValidateAuthTokenResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type ConfirmEmailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmEmailResponse) Reset() {
	*x = ConfirmEmailResponse{}
	mi := &file_notification_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmEmailResponse) ProtoMessage() {}

func (x *ConfirmEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmEmailResponse.ProtoReflect.Descriptor instead.
func (*ConfirmEmailResponse) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{6}
}

func (x *ConfirmEmailResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type UpdateReceiveEmailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReceiveEmail  bool                   `protobuf:"varint,1,opt,name=receive_email,json=receiveEmail,proto3" json:"receive_email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateReceiveEmailResponse) Reset() {
	*x = UpdateReceiveEmailResponse{}
	mi := &file_notification_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateReceiveEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateReceiveEmailResponse) ProtoMessage() {}

func (x *UpdateReceiveEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateReceiveEmailResponse.ProtoReflect.Descriptor instead.
func (*UpdateReceiveEmailResponse) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateReceiveEmailResponse) GetReceiveEmail() bool {
	if x != nil {
		return x.ReceiveEmail
	}
	return false
}

var File_notification_proto protoreflect.FileDescriptor

const file_notification_proto_rawDesc = "" +
	"\n" +
	"\x12notification.proto\x12\x05proto\"9\n" +
	"\x15SetUpAuthTokenRequest\x12 \n" +
	"\fuser_chat_id\x18\x01 \x01(\x03R\n" +
	"userChatId\"R\n" +
	"\x18ValidateAuthTokenRequest\x12 \n" +
	"\fuser_chat_id\x18\x01 \x01(\x03R\n" +
	"userChatId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"+\n" +
	"\x13ConfirmEmailRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"=\n" +
	"\x19UpdateReceiveEmailRequest\x12 \n" +
	"\fuser_chat_id\x18\x01 \x01(\x03R\n" +
	"userChatId\".\n" +
	"\x16SetUpAuthTokenResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"+\n" +
	"\x19ValidateAuthTokenResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"&\n" +
	"\x14ConfirmEmailResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"A\n" +
	"\x1aUpdateReceiveEmailResponse\x12#\n" +
	"\rreceive_email\x18\x01 \x01(\bR\freceiveEmail2\xe0\x02\n" +
	"\x13NotificationService\x12M\n" +
	"\x0eSetUpAuthToken\x12\x1c.proto.SetUpAuthTokenRequest\x1a\x1d.proto.SetUpAuthTokenResponse\x12V\n" +
	"\x11ValidateAuthToken\x12\x1f.proto.ValidateAuthTokenRequest\x1a .proto.ValidateAuthTokenResponse\x12G\n" +
	"\fConfirmEmail\x12\x1a.proto.ConfirmEmailRequest\x1a\x1b.proto.ConfirmEmailResponse\x12Y\n" +
	"\x12UpdateReceiveEmail\x12 .proto.UpdateReceiveEmailRequest\x1a!.proto.UpdateReceiveEmailResponseB\x1aZ\x18notification/proto;protob\x06proto3"

var (
	file_notification_proto_rawDescOnce sync.Once
	file_notification_proto_rawDescData []byte
)

func file_notification_proto_rawDescGZIP() []byte {
	file_notification_proto_rawDescOnce.Do(func() {
		file_notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notification_proto_rawDesc), len(file_notification_proto_rawDesc)))
	})
	return file_notification_proto_rawDescData
}

var file_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_notification_proto_goTypes = []any{
	(*SetUpAuthTokenRequest)(nil),      // 0: proto.SetUpAuthTokenRequest
	(*ValidateAuthTokenRequest)(nil),   // 1: proto.ValidateAuthTokenRequest
	(*ConfirmEmailRequest)(nil),        // 2: proto.ConfirmEmailRequest
	(*UpdateReceiveEmailRequest)(nil),  // 3: proto.UpdateReceiveEmailRequest
	(*SetUpAuthTokenResponse)(nil),     // 4: proto.SetUpAuthTokenResponse
	(*ValidateAuthTokenResponse)(nil),  // 5: proto.ValidateAuthTokenResponse
	(*ConfirmEmailResponse)(nil),       // 6: proto.ConfirmEmailResponse
	(*UpdateReceiveEmailResponse)(nil), // 7: proto.UpdateReceiveEmailResponse
}
var file_notification_proto_depIdxs = []int32{
	0, // 0: proto.NotificationService.SetUpAuthToken:input_type -> proto.SetUpAuthTokenRequest
	1, // 1: proto.NotificationService.ValidateAuthToken:input_type -> proto.ValidateAuthTokenRequest
	2, // 2: proto.NotificationService.ConfirmEmail:input_type -> proto.ConfirmEmailRequest
	3, // 3: proto.NotificationService.UpdateReceiveEmail:input_type -> proto.UpdateReceiveEmailRequest
	4, // 4: proto.NotificationService.SetUpAuthToken:output_type -> proto.SetUpAuthTokenResponse
	5, // 5: proto.NotificationService.ValidateAuthToken:output_type -> proto.ValidateAuthTokenResponse
	6, // 6: proto.NotificationService.ConfirmEmail:output_type -> proto.ConfirmEmailResponse
	7, // 7: proto.NotificationService.UpdateReceiveEmail:output_type -> proto.UpdateReceiveEmailResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_notification_proto_init() }
func file_notification_proto_init() {
	if File_notification_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notification_proto_rawDesc), len(file_notification_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_notification_proto_goTypes,
		DependencyIndexes: file_notification_proto_depIdxs,
		MessageInfos:      file_notification_proto_msgTypes,
	}.Build()
	File_notification_proto = out.File
	file_notification_proto_goTypes = nil
	file_notification_proto_depIdxs = nil
}
